[package]
name = "poke-speare"
version = "0.1.0"
authors = ["MarcoIeni"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["full"] }
anyhow = "1.0"
